### ISSUE TITLE
Can't install Prestashop with generated data because of Faker dependency

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/prestashop-shop-creator#11]
**Describe the bug and add screenshots**
Previously reported here: https://github.com/PrestaShop/PrestaShop/issues/28726#issuecomment-1157445893
![image](https://user-images.githubusercontent.com/16067358/191475272-0e12abd5-786e-4a7f-8557-e02041f5102d.png)

**Steps to reproduce**

1. git clone https://github.com/PrestaShop/prestashop-shop-creator.git
2. cd prestashop-shop-creator
3. composer install
4. php app/console.php
5. Install PrestaShop with the generated data
6. See error

**Solution**
Under Vendor/fakerphp/faker/src/Facker/Provider/Image.php, add the line below after this line `curl_setopt($ch, CURLOPT_FILE, $fp);`
`curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:17.0) Gecko/20100101 Firefox/17.0');`

**Comment by mflasquin** [comment]
I reproduce the issue, I will check how can I fix it

**Comment by khouloudbelguith** [comment]
Hello,

I tried to install PS8.0.0 using data generated with shop-creator => OK
![image](https://user-images.githubusercontent.com/16067358/204014244-c2fafd78-83f3-405d-b9f5-179ba515f583.png)
![image](https://user-images.githubusercontent.com/16067358/204014295-1e0e147a-2a75-4c81-ab8b-1c6ad9ccb5a3.png)

Thanks!
