### ISSUE TITLE
Shop creator generates XML files that generate errors when used with PrestaShop 8.0.0

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/prestashop-shop-creator#13]
**Describe the bug and add screenshots**
The shop creator is not compatible with PS8.0.0, we have errors during the install
![80x_shop_creator](https://user-images.githubusercontent.com/16067358/191477260-6a44a613-8447-4127-82be-49987f66dce5.png)
**Steps to reproduce**
1. `git clone https://github.com/PrestaShop/prestashop-shop-creator.git`
2. `cd prestashop-shop-creator`
3. Under Vendor/fakerphp/src/Facker/Provider/Image.php, add the line below after this line `curl_setopt($ch, CURLOPT_FILE, $fp);`
4. `curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:17.0) Gecko/20100101 Firefox/17.0');`
5. Execute `composer install`
6. Setup the number of data you wish for each categories 
7. `php app/console.php`
8. Begin installation of PrestaShop and stop at database configuration step
9. Move generated data to install/fixtures/fashion folder of PrestaShop installation
10. Under fashion/data, replace `dni=""` by `dni="12345678A"` in `address.xml` generated file.
11. Continue installation
12. See error

**Comment by yanmakouf** [comment]
I'll check it 👍

**Comment by yanmakouf** [comment]
Hello @khouloudbelguith, I can't seem to reproduce this bug. I've tried with php 7&8,  installation works fine to me. Also in the steps to reproduces you described, at step 10, I have no dni="" to replace ->
![Capture d’écran 2022-11-28 à 10 20 54](https://user-images.githubusercontent.com/55691343/204240326-d17b1070-76f0-4dee-bf0d-ea88cbb1273e.png)

**Comment by yanmakouf** [comment]
Friendle reminder @khouloudbelguith :)

**Comment by MhiriFaten** [comment]
Hello @yanmakouf ,

I followed the steps mentioned in the **Steps to reproduce** and found the same problem. 

Here is the screenshot 
![image](https://user-images.githubusercontent.com/111756615/207898656-c2cfbf76-e091-4059-89e2-080a2f89ea38.png)

**Comment by matks** [comment]
Hello guys I changed the ticket title as it is not really a compatibility problem, it is rather an error problem.

@FabienPapet started exploring this problem. It seems, and the screenshot seems to confirm it, that there is a problem in the XML file generated.

So we know what is the wrong XML but we would like to know _what should be the expected XML_ ? 😄 We know what _we dont want_ but what do we want instead?

I put the ticket in "Blocked" for now and I think Fabien's available if you need to discuss with him what he needs to fix this problem 😉
