### ISSUE TITLE
Incompatibility PHP >= 8.0

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/prestashop-shop-creator#28]
The `composer.json` file defines the compatibility for PHP to `>=7.0.0`.

But with PHP 8.0/8.1/8.2, I have these errors : 
![image](https://user-images.githubusercontent.com/1533248/199984680-d0ce2f36-ec6d-47a3-9481-d8fe7d246ee9.png)

**Comment by mflasquin** [comment]
You were faster than me to create the issue :stuck_out_tongue:

**Comment by yanmakouf** [comment]
Hello @Progi1984 a fix was merged on 9 nov
