### ISSUE TITLE
Property "Address->dni" in the generated addresses is empty with Prestashop

### ISSUE THREAD

**Issue by ghost** [PrestaShop/prestashop-shop-creator#8]
Hi @Progi1984, guys, 

Hope you are all well !

I know that you do not reply to issues from this repository but I try :-)

I used your creator for generating more data for fixtures but I have the following error when I try to install them with the index_cli.php file.
![image](https://user-images.githubusercontent.com/16067358/191476949-dbe8a600-1854-4812-b127-689a6975d14b.png)

<img width="463" alt="Screenshot 2021-02-05 at 06 53 35" src="https://user-images.githubusercontent.com/1963546/106995303-e0345b80-677e-11eb-85ea-12f5748a0d05.png">

Is there any way to ignore such errors ? Is there something to do for fixing it ?

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by khouloudbelguith** [comment]
Hello,

Issue fixed 
![image](https://user-images.githubusercontent.com/16067358/204011207-f32612af-7c53-4da5-989a-b4d37da8145a.png)
